### PR TITLE
add pytorch flag

### PR DESCRIPTION
**Pull request by gusye1234**
See more descriptions [here](https://github.com/bytecodealliance/wasi-nn/pull/63)

### CODE REVIEW

**Review by abrown — APPROVED** [review]

**Review by mingqiusun — APPROVED** [review]

**Comment by abrown** [comment]
@gusye1234, looks like the `wasi-nn.abi.md` file needs to be updated as well. Apologies for all of the thrash on this but this WIT syntax and tooling is still relatively new and some of the initial wrinkles still have to be ironed out. In #26, I added a `CONTRIBUTING.md` file that should explain how to use `wit-abi` to auto-generate the ABI file. Can you run those steps in this branch?

**Comment by gusye1234** [comment]
Thanks for the detailed description!
Seem like [wit-abi](https://github.com/WebAssembly/wasi-tools) changed a little bit and unable to parse `wit.md` now, I ran into the error:
```
Error: failed to parse input "/Users/gus/Desktop/wasm/wasi-nn-spec/wasi-nn.wit.md"

Caused by:
    expected `type`, `resource`, or `func`, found '('
         --> /Users/gus/Desktop/wasm/wasi-nn-spec/wasi-nn.wit.md:90:15
          |
       90 | load: function(builder: graph-builder-array, encoding: graph-encoding, target: execution-target) -> expected<graph, error>
```
I used `tags/wit-abi-0.4.0` for `wit-abi`, which I thought was the same version as the CI?

**Comment by abrown** [comment]
Hm, well things are changing quickly in the WIT world. I seem to remember `function` being changed to `func` recently in the WIT syntax. I'll investigate more on Monday because it is unclear to me why the tool is failing if it matches the CI version.

**Comment by gusye1234** [comment]
> Hm, well things are changing quickly in the WIT world. I seem to remember `function` being changed to `func` recently in the WIT syntax. I'll investigate more on Monday because it is unclear to me why the tool is failing if it matches the CI version.

My bad! I looked down into the CI, and found out the tag for `wit-abi` is `wit-abi-0.2.0`. Now everything works perfectly!

**Pull request merged**
