### PR TITLE
Update *.witx files for the witx 0.9 syntax

### PR DESCRIPTION
**Pull request by alexcrichton**
This is a preparatory PR to follow-up from https://github.com/WebAssembly/WASI/pull/395

This commit merges the current WASI main branch into this repository and then adds a commit on top which updates the `*.witx` files to follow the new conventions, notably around type names and result types.

### CODE REVIEW

**Comment by alexcrichton** [comment]
It's also worth noting that this probably shouldn't get merged until https://github.com/WebAssembly/WASI/pull/395 is merged, at which point in time I'll rebase.

**Comment by alexcrichton** [comment]
Ok should be good for merging now. The changes specific to this proposal are in https://github.com/WebAssembly/wasi-nn/pull/13/commits/2706bceef3bbac17043649932e1b8761eb69f3c3

**Review by abrown — APPROVED** [review]
Makes sense to me (except for the `(expected ...)` stuff but I think it looks roughly like we are defining the two sides of a `result`; perhaps it should be more symmetrical, e.g., `(result $r (expected $thing) (error $errno))`?).

**Comment by alexcrichton** [comment]
Ah I'm just lifting the syntax from https://github.com/WebAssembly/interface-types/blob/master/proposals/interface-types/Explainer.md#interface-types

**Pull request merged**
